export enum FeedbackStatus {
  NEW = 'NEW',

  SENT_TO_SUPERVISOR = 'SENT_TO_SUPERVISOR',

  SAVE_AS_DRAFT = 'SAVE_AS_DRAFT',

  APPROVED = 'APPROVED',

  REJECTED = 'REJECTED',

  PENDING_FOR_ASSESSMENT = 'PENDING_FOR_ASSESSMENT',

  COMPLETED = 'COMPLETED',
}
